****************
Developer Manual
****************


Module Description
==================

.. toctree::
   :maxdepth: 2
   :caption: Contents:

.. automodule:: python_library
   :members:


Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`


Library Development Reference
=============================

The code and structure of the project was based on the project: https://github.com/twilio/twilio-python
