language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle
  
before_script:
  - chmod u+x ./gradlew
  
script:
  - ./gradlew clean build -i --continue
