language: java

jdk:
  - oraclejdk8

os:
  - linux

git:
  submodules: true

branches:
  only:
    - master
  
cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew clean build
