trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseGitVersion@5
  inputs:
    versionSpec: 'x.x.x'

- script: |
    make ci-build -e VERSION=$(GitVersion.SemVer)
  env:
    AZURE_DEVOPS_PACKAGE_TOKEN: $(System.AccessToken)
  displayName: 'CI Build'
