trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    make ci-build -e VERSION=$(GitVersion.SemVer)
  env:
    AZURE_DEVOPS_PACKAGE_TOKEN: $(System.AccessToken)
  displayName: 'CI Build'
